version: '3'

volumes:
  xaxaton_base:

services:
  pg_db:
    image: postgres
    restart: unless-stopped
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    tty: True
    volumes:
      - xaxaton_base:/var/lib/postgresql/data

  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: api
    container_name: api
    env_file:
      - .env
    ports:
      - "0.0.0.0:5000:5000"
    restart: always
    tty: True
